### ISSUE TITLE
USER STORY: Favourite

### ISSUE THREAD

**Issue by fredboys** [fredboys/compare-mate#11]
As a logged in user I can favourite a product so that I save it for later if I want to come back

# Acceptance Criteria

* User can click a favourite button
* Count is immediately updated and colour changes
* Favourited products can be accessed at the Favourite Button in NavBar

# Tasks 

- [x] Create favourite button 
- [x] Create handleClick function
- [x] Link the favourite button in the NavBar to these saved posts by the specific user
- [x] Test functionality
