### ISSUE TITLE
USER STORY: Category Search

### ISSUE THREAD

**Issue by fredboys** [fredboys/compare-mate#13]
As a user, I can search for products by category, so that I can find the products I am most interested in.

# Acceptance Criteria

* User can select a category from the dropdown and only the products with that specific category are shown in the feed

# Tasks

- [x] Inside the useEffect add category_type to the fetchproducts url
- [x] Create a ChoiceDropDown component 
- [x] Import ChoiceDropDown into a new Form Control
