### ISSUE TITLE
USER STORY: Edit Post

### ISSUE THREAD

**Issue by fredboys** [fredboys/compare-mate#18]
As a post owner I can edit my product name, description, price, location, link, category so that I can make corrections or update my post after it was created

# Acceptance Criteria

* Three dots on the product page
* Edit button takes you to the CreateProductForm
* All original inputs are saved in the form
* Once saved it updates correctly 

# Tasks

- [x] Create ProductEditForm
- [x] Create three dots on product page
- [x] retrieve original data 
- [x] Import Edit form into product page
- [x] Test functionality
