### ISSUE TITLE
USER STORY: Create Product Posts

### ISSUE THREAD

**Issue by fredboys** [fredboys/compare-mate#8]
As a logged in user I can create posts so that I can share my product deals

# Acceptance Criteria

* Add product button is visible in the NavBar
* User is taken to the create product form
* User can upload image and enter details
* User is notified if error
* User can post

# Tasks

- [x] Create Product Form
- [x] Set up error messages on inputs
- [x] Allow users to Post the product
